export const GET_ALL_CONTEST_LIST = 'GET_ALL_CONTEST_LIST';
export const GET_ALL_CONTEST_LIST_SUCCESS = 'GET_ALL_CONTEST_LIST_SUCCESS';
export const GET_ALL_CONTEST_LIST_ERROR = 'GET_ALL_CONTEST_LIST_ERROR';

export const GET_ALL_CONTEST_MEMBER_LIST = 'GET_ALL_CONTEST_MEMBER_LIST';
export const GET_ALL_CONTEST_MEMBER_LIST_SUCCESS =
  'GET_ALL_CONTEST_MEMBER_LIST_SUCCESS';
export const GET_ALL_CONTEST_MEMBER_LIST_ERROR =
  'GET_ALL_CONTEST_MEMBER_LIST_ERROR';
export const CREATE_CONTEST_MEMBER_LIST = 'CREATE_CONTEST_MEMBER_LIST';
export const CREATE_CONTEST_MEMBER_LIST_SUCCESS =
  'CREATE_CONTEST_MEMBER_LIST_SUCCESS';
export const CREATE_CONTEST_MEMBER_LIST_ERROR =
  'CREATE_CONTEST_MEMBER_LIST_ERROR';
export const UPDATE_CONTEST_MEMBER_LIST = 'UPDATE_CONTEST_MEMBER_LIST';
export const UPDATE_CONTEST_MEMBER_LIST_SUCCESS =
  'UPDATE_CONTEST_MEMBER_LIST_SUCCESS';
export const UPDATE_CONTEST_MEMBER_LIST_ERROR =
  'UPDATE_CONTEST_MEMBER_LIST_ERROR';
export const DELETE_ALL_CONTEST_MEMBER_LIST = 'DELETE_ALL_CONTEST_MEMBER_LIST';
export const DELETE_ALL_CONTEST_MEMBER_LIST_SUCCESS =
  'DELETE_ALL_CONTEST_MEMBER_LIST_SUCCESS';
export const DELETE_ALL_CONTEST_MEMBER_LIST_ERROR =
  'DELETE_ALL_CONTEST_MEMBER_LIST_ERROR';

export const CREATE_CONTEST_LIST = 'CREATE_CONTEST_LIST';
export const CREATE_CONTEST_LIST_SUCCESS = 'CREATE_CONTEST_LIST_SUCCESS';
export const CREATE_CONTEST_LIST_ERROR = 'CREATE_CONTEST_LIST_ERROR';
export const UPDATE_CONTEST_LIST = 'UPDATE_CONTEST_LIST';
export const UPDATE_CONTEST_LIST_SUCCESS = 'UPDATE_CONTEST_LIST_SUCCESS';
export const UPDATE_CONTEST_LIST_ERROR = 'UPDATE_CONTEST_LIST_ERROR';
export const DELETE_CONTEST_LIST = 'DELETE_CONTEST_LIST';
export const DELETE_CONTEST_LIST_SUCCESS = 'DELETE_CONTEST_LIST_SUCCESS';
export const DELETE_CONTEST_LIST_ERROR = 'DELETE_CONTEST_LIST_ERROR';

export const GET_ALL_CONTEST_TYPE = 'GET_ALL_CONTEST_TYPE';
export const GET_ALL_CONTEST_TYPE_SUCCESS = 'GET_ALL_CONTEST_TYPE_SUCCESS';
export const GET_ALL_CONTEST_TYPE_ERROR = 'GET_ALL_CONTEST_TYPE_ERROR';

export const GET_ALL_CONTEST_PRODUCT = 'GET_ALL_CONTEST_PRODUCT';
export const GET_ALL_CONTEST_PRODUCT_SUCCESS =
  'GET_ALL_CONTEST_PRODUCT_SUCCESS';
export const GET_ALL_CONTEST_PRODUCT_ERROR = 'GET_ALL_CONTEST_PRODUCT_ERROR';

export const GET_ALL_CONTEST_INNOVATION = 'GET_ALL_CONTEST_INNOVATION';
export const GET_ALL_CONTEST_INNOVATION_SUCCESS =
  'GET_ALL_CONTEST_INNOVATION_SUCCESS';
export const GET_ALL_CONTEST_INNOVATION_ERROR =
  'GET_ALL_CONTEST_INNOVATION_ERROR';

export const GET_ALL_CONTEST_TECH = 'GET_ALL_CONTEST_TECH';
export const GET_ALL_CONTEST_TECH_SUCCESS = 'GET_ALL_CONTEST_TECH_SUCCESS';
export const GET_ALL_CONTEST_TECH_ERROR = 'GET_ALL_CONTEST_TECH_ERROR';

export const GET_ALL_CONTEST_COUNTRY = 'GET_ALL_CONTEST_COUNTRY';
export const GET_ALL_CONTEST_COUNTRY_SUCCESS =
  'GET_ALL_CONTEST_COUNTRY_SUCCESS';
export const GET_ALL_CONTEST_COUNTRY_ERROR = 'GET_ALL_CONTEST_COUNTRY_ERROR';

export const GET_ALL_CONTEST_PRIZE_CURRENCY = 'GET_ALL_CONTEST_PRIZE_CURRENCY';
export const GET_ALL_CONTEST_PRIZE_CURRENCY_SUCCESS =
  'GET_ALL_CONTEST_PRIZE_CURRENCY_SUCCESS';
export const GET_ALL_CONTEST_PRIZE_CURRENCY_ERROR =
  'GET_ALL_CONTEST_PRIZE_CURRENCY_ERROR';

export const GET_ALL_CONTEST_GLOBAL_DESCRIPTION =
  'GET_ALL_CONTEST_GLOBAL_DESCRIPTION';
export const GET_ALL_CONTEST_GLOBAL_DESCRIPTION_SUCCESS =
  'GET_ALL_CONTEST_GLOBAL_DESCRIPTION_SUCCESS';
export const GET_ALL_CONTEST_GLOBAL_DESCRIPTION_ERROR =
  'GET_ALL_CONTEST_GLOBAL_DESCRIPTION_ERROR';

export const GET_ALL_CONTEST_OFFICIAL = 'GET_ALL_CONTEST_OFFICIAL';
export const GET_ALL_CONTEST_OFFICIAL_SUCCESS =
  'GET_ALL_CONTEST_OFFICIAL_SUCCESS';
export const GET_ALL_CONTEST_OFFICIAL_ERROR = 'GET_ALL_CONTEST_OFFICIAL_ERROR';

export const GET_ALL_CONTEST_MARKET = 'GET_ALL_CONTEST_MARKET';
export const GET_ALL_CONTEST_MARKET_SUCCESS = 'GET_ALL_CONTEST_MARKET_SUCCESS';
export const GET_ALL_CONTEST_MARKET_ERROR = 'GET_ALL_CONTEST_MARKET_ERROR';

export const GET_ALL_CONTEST_DESCRIPTION = 'GET_ALL_CONTEST_DESCRIPTION';
export const GET_ALL_CONTEST_DESCRIPTION_SUCCESS =
  'GET_ALL_CONTEST_DESCRIPTION_SUCCESS';
export const GET_ALL_CONTEST_DESCRIPTION_ERROR =
  'GET_ALL_CONTEST_DESCRIPTION_ERROR';
export const CREATE_CONTEST_DESCRIPTION = 'CREATE_CONTEST_DESCRIPTION';
export const CREATE_CONTEST_DESCRIPTION_SUCCESS =
  'CREATE_CONTEST_DESCRIPTION_SUCCESS';
export const CREATE_CONTEST_DESCRIPTION_ERROR =
  'CREATE_CONTEST_DESCRIPTION_ERROR';
export const UPDATE_CONTEST_DESCRIPTION = 'UPDATE_CONTEST_DESCRIPTION';
export const UPDATE_CONTEST_DESCRIPTION_SUCCESS =
  'UPDATE_CONTEST_DESCRIPTION_SUCCESS';
export const UPDATE_CONTEST_DESCRIPTION_ERROR =
  'UPDATE_CONTEST_DESCRIPTION_ERROR';
export const DELETE_CONTEST_DESCRIPTION = 'DELETE_CONTEST_DESCRIPTION';
export const DELETE_CONTEST_DESCRIPTION_SUCCESS =
  'DELETE_CONTEST_DESCRIPTION_SUCCESS';
export const DELETE_CONTEST_DESCRIPTION_ERROR =
  'DELETE_CONTEST_DESCRIPTION_ERROR';

export const GET_ALL_CONTEST_ENTRY = 'GET_ALL_CONTEST_ENTRY';
export const GET_ALL_CONTEST_ENTRY_SUCCESS = 'GET_ALL_CONTEST_ENTRY_SUCCESS';
export const GET_ALL_CONTEST_ENTRY_ERROR = 'GET_ALL_CONTEST_ENTRY_ERROR';
export const DELETE_CONTEST_ENTRY = 'DELETE_CONTEST_ENTRY';
export const DELETE_CONTEST_ENTRY_SUCCESS = 'DELETE_CONTEST_ENTRY_SUCCESS';
export const DELETE_CONTEST_ENTRY_ERROR = 'DELETE_CONTEST_ENTRY_ERROR';
