export const GET_ALL_COURSE_STRUCTURE = 'GET_ALL_COURSE_STRUCTURE';
export const GET_ALL_COURSE_STRUCTURE_SUCCESS =
  'GET_ALL_COURSE_STRUCTURE_SUCCESS';
export const GET_ALL_COURSE_STRUCTURE_ERROR = 'GET_ALL_COURSE_STRUCTURE_ERROR';
export const GET_SINGLE_COURSE_STRUCTURE = 'GET_SINGLE_COURSE_STRUCTURE';
export const GET_SINGLE_COURSE_STRUCTURE_SUCCESS =
  'GET_SINGLE_COURSE_STRUCTURE_SUCCESS';
export const GET_SINGLE_COURSE_STRUCTURE_ERROR =
  'GET_SINGLE_COURSE_STRUCTURE_ERROR';
export const CREATE_COURSE_STRUCTURE = 'CREATE_COURSE_STRUCTURE';
export const CREATE_COURSE_STRUCTURE_SUCCESS =
  'CREATE_COURSE_STRUCTURE_SUCCESS';
export const CREATE_COURSE_STRUCTURE_ERROR = 'CREATE_COURSE_STRUCTURE_ERROR';
export const UPDATE_COURSE_STRUCTURE = 'UPDATE_COURSE_STRUCTURE';
export const UPDATE_COURSE_STRUCTURE_SUCCESS =
  'UPDATE_COURSE_STRUCTURE_SUCCESS';
export const UPDATE_COURSE_STRUCTURE_ERROR = 'UPDATE_COURSE_STRUCTURE_ERROR';
export const DELETE_COURSE_STRUCTURE = 'DELETE_COURSE_STRUCTURE';
export const DELETE_COURSE_STRUCTURE_SUCCESS =
  'DELETE_COURSE_STRUCTURE_SUCCESS';
export const DELETE_COURSE_STRUCTURE_ERROR = 'DELETE_COURSE_STRUCTURE_ERROR';
